python:
  - 3.7
numpy:
  - 1.14
# these are centralized here so that they are shared between the numpy and numpy-metapackage recipes
numpy_version:
  - 1.18.1
numpy_sha:
  - b6ff59cee96b454516e47e7721098e6ceebef435e3e21ac2d6c3b8b02628eb77