package:
  name: mylib
  version: "v1.0"

source:
  git_rev: tags/v1.0
  git_url: https://github.com/mohsu/mylib.git

requirements:
  build:
    - python
    - setuptools

about:
  home: https://github.com/mohsu