package:
  name: mylib
  version: "v1.0"

source:
  git_rev: https://github.com/mohsu/mylib.git
  git_url: https://github.com/mohsu/mylib.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/mohsu