package:
  name: mylib
  version: "v1.0"

source:
  git_rev: tags/v1.0
  git_url: git@github.com:mohsu/mylib.git

requirements:
  build:
    - python 3.7
    - setuptools
    - numpy >=1.18
  run:
    - python 3.7
    - tensorflow >=2.2
    - pynvml
    - requests
    - matplotlib
    - loguru
    - imgaug
    - numpy >=1.18
    - matplotlib

about:
  home: https://github.com/mohsu