package:
  name: mylib
  version: 1.0

source:
  git_rev:
  git_url: https://github.com/mohsu/mylib.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: