package:
  name: utils
  version: "1.0"

source:
  git_rev: tags/1.0
  git_url: git@github.com:mohsu/mylib.git

#build:
#  noarch: python
#  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
    - numpy >=1.18
  run:
    - python >=3.6
    - tensorflow=2.1.0
    - pynvml
    - requests
    - matplotlib
    - loguru
    - imgaug=0.4.0
    - numpy >=1.18
    - matplotlib
    - opencv=4.2.0

about:
  home: https://github.com/mohsu